export const verifiedActions = ["actions/stale", "actions/first-interaction", "actions/download-artifact", "actions/upload-artifact", "actions/cache", "actions/setup-node",
"actions/setup-go", "actions/setup-java", "actions/setup-dotnet", "getsentry/action-git-diff-suggestions", "psalm/psalm-github-security-scan",
"ponicode/azure-devops-npm-action", "aws-actions/codeguru-reviewer", "redhat-actions/oc-installer", "codacy/git-version", "redhat-actions/kn-service-manager",
"redhat-actions/openshift-actions-runner-installer", "parasoft/deploy-environment-action", "parasoft/disconnect-server-action",
"parasoft/execute-job-action", "parasoft/destroy-environment-action", "parasoft/run-dottest-action", "fortify/gha-export-vulnerabilities",
"parasoft/run-cpptest-action", "redhat-actions/oc-new-app", "buildkite/trigger-pipeline-action", "codeclimate/velocity-deploy-action",
"coverallsapp/github-action", "Axosoft/glo-action-parse-links", "Axosoft/glo-action-label-card", "Axosoft/glo-action-assign-card",
"Axosoft/glo-action-comment-card", "Axosoft/glo-action-move-card", "GorillaStack/github-action-apply-on-merge", "codefresh-io/codefresh-pipeline-runner",
"twilio-labs/actions-sms", "pulumi/setup-pulumi", "whitesource/GitHubPackagesSecurityAction", "aws-actions/amazon-ecs-deploy-task-definition",
"aws-actions/amazon-ecs-render-task-definition", "aws-actions/amazon-ecr-login", "aws-actions/configure-aws-credentials", "snyk/actions",
"calibreapp/image-actions", "sysdiglabs/k8s-security-configwatch", "psalm/psalm-github-actions", "snyk/release-notes-preview",
"aws-actions/aws-cloudformation-github-deploy", "google/secrets-sync-action", "hashicorp/packer-github-actions", "bridgecrewio/bridgecrew-action",
"hashicorp/gh-action-check-broken-links", "aws-actions/amazon-eks-fargate", "fortify/gha-setup-scancentral-client", "fortify/gha-setup-fod-uploader",
"fortify/gha-fod-generate-sarif", "RapidAPI/gh-api-testing-trigger", "RIGS-IT/xanitizer-action", "lightstep/lightstep-action-predeploy",
"lightstep/lightstep-action-snapshot", "Teamwork/github-sync", "pachyderm/pachyderm-actions", "SecureCodeWarrior/github-action-add-sarif-contextual-training",
"ServiceNow/sncicd-tests-run", "ServiceNow/sncicd-publish-app", "ServiceNow/sncicd-plugin-activate", "ServiceNow/sncicd-rollback-app",
"ServiceNow/sncicd-apply-changes", "ServiceNow/sncicd-install-app", "ServiceNow/sncicd-plugin-rollback", "defensecode/thunderscan-action",
"redhat-actions/oc-login", "ServiceNow/sncicd-batch-install", "bridgecrewio/yor-action", "SonarSource/sonarqube-quality-gate-action",
"aquasecurity/tracee-action", "ServiceNow/sncicd-instance-scan", "Checkmarx/kics-github-action", "algolia/algoliasearch-crawler-github-actions",
"devops-actions/json-to-file", "SecureStackCo/actions-all-in-one", "redhat-actions/chart-verifier", "aws-actions/setup-sam",
"Verimatrix/app-shield-protect", "redhat-actions/openshift-tools-installer", "redhat-actions/openshift-tools-installer",
"cloudflare/wrangler-action", "cloud-maker-ai/github-action-deploy", "databricks/upload-dbfs-temp", "bitovi/github-actions-aws-secrets-manager",
"synopsys-sig/coverity-report-output-v7-json", "nobl9/nobl9-action", "checkmarx-ts/checkmarx-cxflow-github-action", "redhat-actions/buildah-build",
"redhat-actions/push-to-registry", "facebook/pyre-action", "facebook/sapp-action", "facebook/pysa-action", "parasoft/run-jtest-action",
"redhat-actions/crda", "zaproxy/action-baseline", "zaproxy/action-full-scan", "infracost/actions", "Bearer/actions", "OctopusDeploy/install-octopus-cli-action",
"octokit/graphql-action", "octokit/request-action", "getsentry/action-visual-snapshot", "ServiceNow/servicenow-devops-register-package",
"ServiceNow/servicenow-devops-register-artifact", "ServiceNow/servicenow-devops-test-report", "ServiceNow/servicenow-devops-sonar",
"veracode/veracode-sca", "42Crunch/api-security-audit-action", "elmahio/github-create-deployment-action", "elmahio/github-upload-source-map-action",
"redhat-actions/podman-login", "hashicorp/terraform-cdk-action", "google-github-actions/run-vertexai-notebook", "CircleCI-Public/trigger-circleci-pipeline-action",
"google-github-actions/release-please-action", "SonarSource/sonarqube-scan-action", "ponicode/unit-testing-action", "SecureStackCo/actions-code",
"SecureStackCo/actions-log4j", "SecureStackCo/actions-exposure", "SecureStackCo/actions-secrets", "aquasecurity/tfsec-action", "bridgecrewio/checkov-action",
"perforce/setup-p4", "shipa-corp/shipa-gh-action", "synopsys-sig/detect-action", "snyk/driftctl-action", "devops-actions/load-used-actions",
"ionic-team/appflow-build", "DataDog/upload-dsyms-github-action", "Checkmarx/chainalert-github-action", "codacy/codacy-coverage-reporter-action",
"LambdaTest/LambdaTest-tunnel-action", "redhat-actions/s2i-build", "rapid7/insightappsec-scan-github-actions", "game-ci/unity-return-license",
"game-ci/unity-activate", "game-ci/unity-request-activation-file", "mablhq/setup-mabl-cli", "redhat-actions/try-in-web-ide", "dapr/setup-dapr",
"Codesee-io/codesee-detect-languages-action", "Codesee-io/codesee-map-action", "ponicode/dogstring-action", "Asana/comment-on-task-github-action",
"Asana/create-app-attachment-github-action", "ponicode/squar_action", "nowsecure/nowsecure-action", "aquasecurity/cfsec-sarif-action",
"Checkmarx/dustilock", "aquasecurity/build-security-action", "OctopusDeploy/push-build-information-action", "nowsecure/nowsecure-sbom-action",
"veracode/veracode-uploadandscan-action", "sysdiglabs/exporter-builder", "okteto/delete-namespace", "okteto/build", "okteto/deploy-preview",
"okteto/destroy-preview", "okteto/namespace", "okteto/pipeline", "okteto/destroy-pipeline", "okteto/create-namespace", "DataDog/junit-upload-github-action",
"google-github-actions/ssh-compute", "nightfallai/nightfall_dlp_action", "OctopusDeploy/create-release-action", "taktile-org/await-taktile-deployment-action",
"google-github-actions/deploy-cloudrun", "OctopusDeploy/run-runbook-action", "soos-io/soos-sca-github-action", "OctopusDeploy/push-package-action",
"cloudflare/pages-action", "hashicorp/setup-nomad-pack", "datreeio/validate-license-action", "wpengine/github-action-wpe-site-deploy",
"codefresh-io/codefresh-report-image", "digitalocean/app_action", "snaplet/action", "aws-actions/aws-secretsmanager-get-secrets", "matlab-actions/run-build",
"devops-actions/load-runner-info", "devops-actions/issue-comment-tag", "aws-actions/aws-codebuild-run-build", "shundor/python-bandit-scan",
"sysdiglabs/scan-action", "oak9io/oak9.githubaction", "PaloAltoNetworks/prisma-cloud-scan", "armory/cli-deploy-action", "MobSF/mobsfscan",
"stackhawk/hawkscan-action", "ServiceNow/servicenow-devops-change", "codecov/codecov-action", "bitovi/github-actions-deploy-eks-helm",
"algolia/setup-algolia-cli", "anchore/sbom-action", "sigstore/gh-action-sigstore-python", "aliyun/acr-login", "aliyun/ack-set-context",
"aliyun/acr-scan", "TryGhost/action-deploy-theme", "getsentry/action-github-app-token", "aquasecurity/trivy-action", "hashicorp/setup-terraform",
"phylum-dev/phylum-analyze-pr-action", "game-ci/steam-deploy", "veracode/veracode-sandboxes-helper", "aquasecurity/tfsec-pr-commenter-action",
"UffizziCloud/preview-action", "dependabot/fetch-metadata", "dagger/dagger-for-github", "game-ci/unity-test-runner", "jfrog/frogbot",
"apisec-inc/apisec-run-scan", "google-github-actions/auth", "digitalocean/action-doctl", "oracle-actions/setup-java", "mablhq/github-run-tests-action",
"gradle/gradle-build-action", "bitovi/github-actions-react-to-ghp","DataDog/agent-github-action", "synopsys-sig/synopsys-action",
"docker/bake-action", "docker/login-action", "apisec-inc/ethicalcheck-action", "docker/build-push-action", "docker/setup-qemu-action",
"slackapi/slack-github-action", "NuGet/setup-nuget", "snaplet/vercel-action", "ansible/ansible-lint-action", "veracode/Veracode-pipeline-scan-action",
"game-ci/unity-builder", "docker/metadata-action", "jfrog/setup-jfrog-cli", "readmeio/rdme", "liquibase-github-actions/future-rollback-count-sql",
"liquibase-github-actions/generate-changelog", "liquibase-github-actions/init-copy", "liquibase-github-actions/future-rollback-sql",
"liquibase-github-actions/future-rollback-from-tag-sql", "liquibase-github-actions/history", "liquibase-github-actions/init-hub",
"liquibase-github-actions/mark-next-changeset-ran-sql", "liquibase-github-actions/init-start-h2", "liquibase-github-actions/list-locks",
"liquibase-github-actions/migrate", "liquibase-github-actions/mark-next-changeset-ran", "liquibase-github-actions/init-project",
"liquibase-github-actions/rollback-count", "liquibase-github-actions/migrate-sql", "liquibase-github-actions/rollback",
"liquibase-github-actions/release-locks", "liquibase-github-actions/register-changelog", "liquibase-github-actions/rollback-count-sql",
"liquibase-github-actions/rollback-to-date", "liquibase-github-actions/rollback-one-update-sql", "liquibase-github-actions/rollback-one-changeset",
"liquibase-github-actions/rollback-sql", "liquibase-github-actions/rollback-one-changeset-sql", "liquibase-github-actions/rollback-to-date-sql",
"liquibase-github-actions/rollback-one-update", "liquibase-github-actions/snapshot", "liquibase-github-actions/checks-delete",
"liquibase-github-actions/changelog-sync-to-tag", "liquibase-github-actions/calculate-checksum", "liquibase-github-actions/changelog-sync",
"liquibase-github-actions/checks-copy", "liquibase-github-actions/changelog-sync-to-tag-sql", "liquibase-github-actions/checks-reset",
"liquibase-github-actions/checks-customize", "liquibase-github-actions/changelog-sync-sql", "liquibase-github-actions/checks-bulk-set",
"liquibase-github-actions/checks-disable", "liquibase-github-actions/deactivate-changelog", "veracode/veracode-pipeline-scan-results-to-sarif",
"datreeio/action-datree", "rapid7/insightcloudsec-actions", "readmeio/scheduled-milestones", "synopsys-sig/intelligent-security-scan",
"DevCycleHQ/feature-flag-code-usage-action", "DevCycleHQ/feature-flag-pr-insights-action", "anchore/scan-action", "google-github-actions/deploy-appengine",
"readmeio/rdme", "liquibase/liquibase-github-action", "liquibase-github-actions/generate-changelog", "liquibase-github-actions/future-rollback-sql",
"liquibase-github-actions/future-rollback-from-tag-sql", "liquibase-github-actions/history", "liquibase-github-actions/init-hub",
"liquibase-github-actions/mark-next-changeset-ran-sql", "liquibase-github-actions/init-start-h2", "liquibase-github-actions/list-locks",
"liquibase-github-actions/migrate", "liquibase-github-actions/mark-next-changeset-ran", "liquibase-github-actions/init-project",
"liquibase-github-actions/rollback-count", "liquibase-github-actions/migrate-sql", "liquibase-github-actions/rollback", "liquibase-github-actions/release-locks",
"liquibase-github-actions/register-changelog", "liquibase-github-actions/rollback-count-sql", "liquibase-github-actions/rollback-to-date",
"liquibase-github-actions/rollback-one-update-sql", "liquibase-github-actions/rollback-one-changeset", "liquibase-github-actions/rollback-sql",
"liquibase-github-actions/rollback-one-changeset-sql", "liquibase-github-actions/rollback-to-date-sql", "liquibase-github-actions/rollback-one-update",
"liquibase-github-actions/snapshot", "liquibase-github-actions/changelog-sync-sql", "liquibase-github-actions/checks-bulk-set",
"liquibase-github-actions/checks-disable", "liquibase-github-actions/deactivate-changelog", "liquibase-github-actions/db-doc",
"liquibase-github-actions/clear-checksums", "liquibase-github-actions/checks-show", "liquibase-github-actions/checks-enable",
"liquibase-github-actions/checks-run", "liquibase-github-actions/diff-changelog", "liquibase-github-actions/flow", "liquibase-github-actions/execute-sql",
"liquibase-github-actions/flow-validate", "liquibase-github-actions/diff", "liquibase-github-actions/drop-all", "liquibase-github-actions/init-copy",
"liquibase-github-actions/update-one-changeset", "liquibase-github-actions/update-testing-rollback", "liquibase-github-actions/update-count-sql",
"liquibase-github-actions/update-one-changeset-sql", "liquibase-github-actions/update", "liquibase-github-actions/update-count", "liquibase-github-actions/validate",
"liquibase-github-actions/update-sql", "liquibase-github-actions/update-to-tag", "liquibase-github-actions/update-to-tag-sql", "liquibase-github-actions/checks-delete",
"liquibase-github-actions/changelog-sync-to-tag", "liquibase-github-actions/calculate-checksum", "liquibase-github-actions/changelog-sync",
"liquibase-github-actions/checks-copy", "liquibase-github-actions/changelog-sync-to-tag-sql", "liquibase-github-actions/checks-reset",
"liquibase-github-actions/checks-customize", "liquibase-github-actions/unexpected-changesets", "liquibase-github-actions/snapshot-reference",
"liquibase-github-actions/tag-exists", "liquibase-github-actions/status", "liquibase-github-actions/sync-hub", "liquibase-github-actions/tag",
"liquibase-github-actions/future-rollback-count-sql", "atlassian/gajira-cli", "atlassian/gajira-login", "atlassian/gajira-comment",
"atlassian/gajira-create", "atlassian/gajira-find-issue-key", "atlassian/gajira-todo", "atlassian/gajira-transition", "devops-actions/load-available-actions",
"SonarSource/sonarcloud-github-action", "godaddy/tartufo-action", "SonarSource/sonarcloud-github-c-cpp", "cypress-io/github-action",
"google-github-actions/get-gke-credentials", "google-github-actions/upload-cloud-storage", "algosec/connectivity-risk-analysis-action",
"aquasecurity/chain-bench-action", "google-github-actions/deploy-cloud-functions", "oracle-actions/configure-kubectl-oke", "DataDog/synthetics-ci-github-action",
"ruby/setup-ruby", "microsoft/sarif-actions", "Azure/webapps-deploy", "Azure/appservice-settings", "Azure/aci-deploy", "Azure/appservice-build",
"microsoft/vs-intellicode", "Azure/static-web-apps-deploy", "Azure/policy-compliance-scan", "Azure/manage-azure-policy", "microsoft/store-submission",
"Azure/bicep-build-action", "github/ghas-jira-integration", "github/issue-labeler", "github/automatic-contrib-prs", "Azure/k8s-artifact-substitute",
"microsoft/pybryt-action", "Azure/AppConfiguration-Sync", "Azure/k8s-bake", "Azure/acr-build", "actions/delete-package-versions",
"Azure/data-factory-deploy-action", "Azure/pipelines", "Azure/k8s-lint", "microsoft/ps-docs", "Azure/deployment-what-if-action",
"microsoft/install-databricks-cli", "microsoft/scala-style-download", "microsoft/scalastyle-validate", "Azure/azure-resource-login-action",
"Azure/run-sqlpackage-action", "Azure/data-factory-export-action", "microsoft/databricks-import-notebook", "Azure/app-configuration-import-action",
"Azure/aks-create-action", "Azure/data-factory-validate-action", "microsoft/android-app-size-diff", "Azure/spring-cloud-deploy",
"Azure/setup-kubectl", "microsoft/vstest-action", "Azure/k8s-set-context", "microsoft/action-publish-symbols", "microsoft/msvc-code-analysis-action",
"Azure/mysql", "Azure/postgresql", "Azure/Synapse-workspace-deployment", "microsoft/ApplicationInspector-Action", "github/webpack-bundlesize-compare-action",
"Azure/sql-action", "Azure/load-testing", "microsoft/action-python", "microsoft/action-armttk", "github/super-linter", "actions/labeler",
"microsoft/infersharpaction", "Azure/functions-action", "Azure/k8s-deploy", "actions/jekyll-build-pages", "github/lock", "github/privileged-requester",
"microsoft/InclusivenessAnalyzer", "microsoft/RichCodeNavIndexer", "Azure/container-apps-deploy-action", "actions/dependency-review-action",
"Azure/login", "Azure/functions-container-action", "actions/upload-pages-artifact", "actions/setup-python", "Azure/arm-deploy", "actions/add-to-project",
"Azure/powershell", "actions/deploy-pages", "Azure/docker-login", "microsoft/ps-rule", "microsoft/psscriptanalyzer-action", "actions/go-dependency-submission",
"microsoft/PR-Metrics", "github/branch-deploy", "microsoft/DevSkim-Action", "Azure/cli", "Azure/aca-review-apps", "microsoft/playwright-github-action",
"Azure/aks-set-context", "microsoft/setup-msbuild", "actions/checkout", "actions/github-script", "Azure/spring-apps-deploy", "Azure/setup-helm",
"microsoft/security-devops-action", "Azure/build-vm-image", "actions/configure-pages", "Azure/k8s-create-secret", "microsoft/powerplatform-actions"];

